apiVersion: v1
kind: Service
metadata:
  name: api-python
spec:
  selector:
    app: api-python
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    nodePort: 30008

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-python
spec:
  selector:
    matchLabels:
      app: api-python
  replicas: 2
  template:
    metadata:
      labels:
        app: api-python
    spec:
      containers:
      - name: api-python
        image: deadlike/app-python:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: dockerhub

---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: api-python
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: api-python
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 20
