apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-python
spec:
  selector:
    matchLabels:
      app: api-python
  replicas: 1
  template:
    metadata:
      labels:
        app: api-python
    spec:
      containers:
      - name: api-python
        image: deadlike/app-python:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: dockerhub